# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    # Start CI process only when someone pushed to master and dev
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Set up Java
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # Caching Maven dependency for CI perforamnce
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # Build with maven without test
      - name: Build with Maven
        run: mvn package -Dmaven.test.skip=true
  test:
    needs: build # depends on build stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Maven
        # Execute Junit test
        run: mvn test
